#!/bin/bash
                                                                                                                                                          
#  ad88888ba                                        88                          88888888ba                                                                  
# d8"     "8b                                       ""                          88      "8b                                                                 
# Y8,                                                                           88      ,8P                                                                 
# `Y8aaaaa,     ,adPPYba,  8b,dPPYba,  8b       d8  88   ,adPPYba,   ,adPPYba,  88aaaaaa8P'  88       88  8b,dPPYba,   8b,dPPYba,    ,adPPYba,  8b,dPPYba,  
#   `"""""8b,  a8P_____88  88P'   "Y8  `8b     d8'  88  a8"     ""  a8P_____88  88""""88'    88       88  88P'   `"8a  88P'   `"8a  a8P_____88  88P'   "Y8  
#         `8b  8PP"""""""  88           `8b   d8'   88  8b          8PP"""""""  88    `8b    88       88  88       88  88       88  8PP"""""""  88          
# Y8a     a8P  "8b,   ,aa  88            `8b,d8'    88  "8a,   ,aa  "8b,   ,aa  88     `8b   "8a,   ,a88  88       88  88       88  "8b,   ,aa  88          
#  "Y88888P"    `"Ybbd8"'  88              "8"      88   `"Ybbd8"'   `"Ybbd8"'  88      `8b   `"YbbdP'Y8  88       88  88       88   `"Ybbd8"'  88          



#------------------------------------------------------------------------------------
# Initialisation of globals.

set -o nounset
MYDIR=$( dirname "$(readlink -f "$0")" )
source "$MYDIR/variables.sh"
source "$MYDIR/utils.sh"
e=$(printf "\e") 
readonly CODE_S="$e[32m"
readonly CODE_E="$e[0m"

#------------------------------------------------------------------------------------
# showhelp - give some info about the service. SERVICENAME and IMAGENAME are provided by variables.sh.

function showhelp {
cat <<EOF >&2

NAME
   ${SERVICENAME}
       
SYNOPSIS
   ${SERVICENAME} [-a] build
   ${SERVICENAME} [-a] copyup
   ${SERVICENAME} [-a] branch
   ${SERVICENAME} [-a] push 
   
   ${SERVICENAME} configure     
   
DESCRIPTION
   A simple dRunner container from ${IMAGENAME}.
   
EOF
}

#------------------------------------------------------------------------------------
# Run a command in the container. If we had any volumes we'd add in "${DOCKEROPTS[@]}".

function sayinfo { echo -e "[ \e[2m${1}\e[0m ]" ; }
function saygood { echo -e "[ \e[32m${1}\e[0m ]" ; }
function saybad { echo -e "[ \e[31m\e[1m${1}\e[0m ]" ; }

function dockerrun {
   docker run -i --name="${SERVICENAME}-${COMMAND}" -h "${HOSTNAME}" "${IMAGENAME}" "$@"
   local RVAL=$?
   docker rm "${SERVICENAME}-${COMMAND}" >/dev/null
   if [ $RVAL -ne 0 ]; then die "${SERVICENAME} ${COMMAND} failed." ; fi
}

function branch_low {
   local P="$1"
   local BRANCH=$(git rev-parse --abbrev-ref HEAD) || { saybad "$P - not a git repo" ; return 1 ; }
   [ "$BRANCH" = "dev" ] && { saygood "$P - dev" ; return 0 ; }
   [ "$BRANCH" = "master" ] && { sayinfo "$P - master" ; return 0 ; }
   saybad "$P - $BRANCH"   
}

function branch {
   [ -v DEVPATH ] || { branch_low "$PWD" ; return 0 ; }
   
   (
   cd "$DEVPATH"
   for d in */ ; do
      branch_low "$d"
   done
   )
}



# function pushy {
#   ( #subshell
#   cd "/root/dev/$1"
#   BRANCH=$(git rev-parse --abbrev-ref HEAD) || BRANCH="wibble"
#   [ "$BRANCH" = "dev" ] || { sayinfo "On $BRANCH not dev: $d" ; exit 0 ; }
#   [ -e "push" ] || { sayinfo "Doesn't have push script: $D" ; exit 0 ; }
#   ./push || { saybad "FAILED for $1" ; exit 1 ; }
#   saygood "Pushed $d to $BRANCH"
#   )
# }

# for d in */ ; do
#     pushy "$d"
# done


#------------------------------------------------------------------------------------
# The main function. We can add any commands we'd like here!

function main {
   [ "$#" -gt 0 ] || { showhelp ; exit 1 ; }
   COMMAND="${1}" ; shift

   if [ "$COMMAND" = "-a" ]; then
      DEVPATH=$(dockerrun cat /config/path) || die "Call ${SERVICENAME} configure first."
      [ "$#" -gt 0 ] || { showhelp ; exit 1 ; }
      COMMAND="${1}" ; shift      
   fi
   
   case "$COMMAND" in 
   
          #--- standard (required) commands
   
         install)
            ;;
            
         obliterate)
            ;;
                     
         uninstall)
            ;;
                     
         backupstart)
            #BACKUPPATH="$1"
            ;;
         
         backupend)
            #BACKUPPATH="$1"
            ;;
         
         restore)
            #RESTOREPATH="$1"
            ;;
         
         help)
            showhelp
            ;;
         
         enter)
            dockerrun /bin/bash "$@"
            ;;
         
         updatestart)
            ;;

         updateend)
            ;;
         
         selftest)
            ;;
            
         #--- custom commands

         build)
            build
            ;;
            
         copyup)
            copyup
            ;;
            
         branch)
            branch
            ;;
            
         push)
            push
            ;;
            
         #--- unrecognised commands

         *)
            showhelp
            die "Unrecognised command ${CODE_S}${COMMAND}${CODE_E}"            
            ;;
   esac
}

#------------------------------------------------------------------------------------

main "$@"
